### ISSUE TITLE
Testimonial not working

### ISSUE THREAD

**Issue by kuldeep4110** [malithmcr/Magento2-Testimonial-Module#1]
Hello Developer,

   I have tried to install your extension and found there was error in Not registered handle testimonial_testimonial_listing_data_source. After fixing that error I got the new error. When I click on the Add new testimonial under admin it redirect to dashboard.

Can you please  update the extension.

Thanks
Kuldeep

**Comment by malithmcr** [comment]
Hello Kuldeep,

Thanks for the update. Im on it.

**Comment by patruvlad** [comment]
To fix this just check the for the datasources declaration not to be Capitalizes, check the etc/di.xml file and change Testimonials_Testimonial_listing_data_source to testimonials_testimonial_listing_data_source

**Comment by impunkj** [comment]
Hello, 
There is so many bugs on this module like in frontend and backend like, 
in admin can't submit testimonials and from frontend also.

Can i contribute to this project

**Comment by malithmcr** [comment]
Hi @impunkj ,

of course you can contribute to this project and greatly appreciated. please create a pull request with your new changes. I'll review and update also readme file with credits.
