### ISSUE TITLE
Lots of issues

### ISSUE THREAD

**Issue by PrithweemaD** [malithmcr/Magento2-Testimonial-Module#2]
1. Junk codes here & there
2. Listing in admin panel will show handle not registered error
3. Module does not include database table prefix. So if you are setting a prefix, this will throw error.
4. Customer testimonial submit never works. Always thrown to catch statement in controller.
5. Within the module, it contains css file in pub folder instead of view folder.

I have fixed some of the issues in this module. Please find here : https://github.com/PrithweemaD/Extensions/

**Comment by malithmcr** [comment]
Hey,
I'll update the module soon, if you already have any fix could you please create pull request ? 
Thanks.

**Comment by malithmcr** [comment]
Hi @PrithweemaD  could you please create a pull request ? I have also updated the code.  please create Issues separately for each of bugs you see. or help me with fixing :) thank you.
